[theme]
primaryColor = "#e53238"          # FIFA Red
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "viewer"

[logger]
level = "info"

[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false
headless = true
